<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>GamerMX Tool</AssemblyName>
    <RootNamespace>GamerMX.Tool</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>embedded</DebugType>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>1.0.1</Version>
    <Authors>Максимов Д.А.</Authors>
    <Product>GamerMX Tool</Product>
    <Description>Таймер здоровья, заметки и оверлей для геймеров и разработчиков.</Description>
  </PropertyGroup>

</Project>
